### ISSUE TITLE
Question: compiling and adding to project

### ISSUE THREAD

**Issue by marc-vdm** [Alexhuszagh/BreezeStyleSheets#14]
I may want to add this to a project I am working on and have a question on this;
The readme says to compile the style sheets to use them. Does that mean that every user of the project need to compile the dark theme or when does this happen?

If the theme needs to be compiled every time, is there a trick to have this be done automagically on the first time the software runs?

**Comment by rmawatson** [comment]
you suuurely tried this before posting two issues about it........ 

once you have compiled a qrc into a .py file you just import it. This is documented by qt.

**Comment by Alexhuszagh** [comment]
@marc-vdm You can distribute the compiled QRC files (as either a Python file, or by including it as a resource in a Qt5 app, which are portable. Once you've compiled the file (Python) or provided it as a resource, it will do it's magic every time.
