### ISSUE TITLE
QDialogButtonBox minimizes horizontally

### ISSUE THREAD

**Issue by LiviuShiva** [Alexhuszagh/BreezeStyleSheets#15]
First of all, it is a very nice work.

The buttons contained by QDialogButtonBox are minimized like in the image below:

![image](https://user-images.githubusercontent.com/3812469/106029299-9b048f80-60d5-11eb-88eb-1d86808be055.png)

**Comment by Alexhuszagh** [comment]
This has been fixed as of the latest commit. This really wasn't a bug with the stylesheet, however, it's a major UI flaw, so I considered it a worthwhile fix.

See Fusion actually does not have equal widths for the buttons equally with large names either:

![2021-07-16 23_23_20-Sample single widget application](https://user-images.githubusercontent.com/9440903/126025387-9ef68b4d-83a1-45a0-86d1-567ffb60b682.png)

However, the min width is much lower in BreezeStyleSheets, so this should be fixed.

![2021-07-16 23_23_30-Sample single widget application](https://user-images.githubusercontent.com/9440903/126025382-520317f6-1f08-4cc4-b24e-eed4f2120b82.png)

The new version is as follows:

![2021-07-16 23_24_11-Sample single widget application](https://user-images.githubusercontent.com/9440903/126025407-b74ca54a-dd97-4b9d-befe-5860738e7b21.png)

(There's also nice icons which are added to standard buttons, which you can entirely remove if you wish).
