### ISSUE TITLE
Consider supporting githubuser0xFFFF/Qt-Advanced-Docking-System

### ISSUE THREAD

**Issue by ruilvo** [Alexhuszagh/BreezeStyleSheets#20]
Hello

The advanced docking system is really a great docking system for Qt. It uses an internal stylesheet to make it look like this:

![imagem](https://user-images.githubusercontent.com/8402646/126128158-d9a529ca-e585-404a-aacc-ff24bac2148b.png)

When trying to use the stylesheet provided here without any changes, this happens:

![imagem](https://user-images.githubusercontent.com/8402646/126128251-91535f83-ebaa-4cf0-96e0-759d82d8e9f2.png)

What happens is that Qt-ADS uses an internal stylesheet to keep things in order.

If the internal stylesheet is disabled, this happens:

![imagem](https://user-images.githubusercontent.com/8402646/126128365-bf4e8377-10f5-4207-9be2-4fb2835a7a2c.png)

Notice how in particular the icons are wrong (like a double icon in one of them), and the tabs aren't clear, etc.

![imagem](https://user-images.githubusercontent.com/8402646/126128414-391f732a-b981-4d4a-aca0-3e83925409c3.png)

I guess it would require these things: 

https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/tree/master/src/stylesheets

To be included in the theme.

Anyway, thanks for this work! It's amazing!

**Comment by Alexhuszagh** [comment]
The only issue with including these directly into the theme is this library is MIT licensed, which makes it useful for commercial usage, however, the above code is LGPLv2.1 licensed. I'll see if there are any fixes, or provide instructions on how to incorporate the above stylesheet internally, since obviously this is a very useful feature.

**Comment by ruilvo** [comment]
I'm not sure using the names of the stylesheet tags would exactly constitute an LGPL violation. You're not, in any way, using the library... But understand the caution, of course.

**Comment by Alexhuszagh** [comment]
@ruilvo No, that should be fine, as long as I don't base anything off their source code. Their documentation also seems to [publish](https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/blob/master/doc/user-guide.md#activetabhasclosebutton) the tag names, so this should be doable. As an extra precaution, you should be able to just provide the tag names and then I can just play with styles until everything works.

Is there a particular example you want me to base off of (like, a minimal, simple Qt project that I can ensure works before moving onto checking more complicated scenarios work)?

**Comment by ruilvo** [comment]
Those are the config tags, these are the stylesheets:
https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/tree/master/src/stylesheets
I don't have a base application, but I think their examples are a great place to test. 
Btw, they have the "Focus Highlighting feature" that they show in there as a separate file, but it seems it can be easily made into a single stylesheet:
https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/blob/master/doc/user-guide.md#focushighlighting

**Comment by Alexhuszagh** [comment]
@ruilvo Right, I just want to make sure I'm not looking through source files just as an extra precaution to find the tags. However, someone just telling me what all the tags are should be fine. I'll then just use a stock example.

For example, based on the documentation, I can see `ads--CDockWidgetTab[focused="true"]`. If there's any others not covered in the docs, that would be great to know.

**Comment by ruilvo** [comment]
Looking at the code, there's the problem that some of it has to do with the buttons and etc. And if you want to be clean with licensing, you can't copy that. And you can't also override from a "parent" QSS... 
So I guess this can't be fixed from your end... I'll have to write my own.

**Comment by Alexhuszagh** [comment]
At the very least, I should be able to provide "clean" install instructions or scripts that can help isolate this, so we can avoid licensing issues in the main code, but also make it easier to opt-in for compatibility with an LGPL project.

**Comment by Alexhuszagh** [comment]
I'll see what I can, at the very least, something will be more ergonomic than everyone trying to recreate the same solution on their end.

**Comment by Alexhuszagh** [comment]
Ok, this should be doable, and I'll start working on it. As long as I just touch the actual tags they provide, it should be fine. Their official bindings are BSD 3-Clause, and they provide a lot of API documentation, so I can just "play around" without touching the source code.
https://github.com/conda-forge/pyqtads-feedstock

**Comment by ruilvo** [comment]
Thank you for the enthusiastic feedback and willingness!! If there's something you need in the future regarding this topic, get in touch.
Thanks again!

**Comment by Alexhuszagh** [comment]
Do you have a sample set of widgets for the dock widget? I'm reproducing some of the behavior, but I'm not very familiar with the Advanced Docking System, so these are the examples I get. Obviously, the tab is next to unreadable, but child QPushButtons seem to be correct.

![Screenshot_20210719_132435](https://user-images.githubusercontent.com/9440903/126208566-5ede5913-3b95-4f8c-9929-c7d73078e612.png)


![Screenshot_20210719_132409](https://user-images.githubusercontent.com/9440903/126208563-b3c9a58e-6809-4d83-9ab6-f01ac30ce516.png)

See [here](https://github.com/Alexhuszagh/BreezeStyleSheets/blob/master/example/advanced-dock.py) for my sample code.

**Comment by ruilvo** [comment]
Actually, I have never used it with Python. I don't understand exactly what you mean with a set of widgets of ADS but it pretty much just the docking widget and the docking manager. I think you're nest to achieving the right thing. You already have got the tab buttons pretty ironed out. Sorry, I didn't understand what you want exactly.

**Comment by Alexhuszagh** [comment]
I've got a fairly rough initial demo, and it seems to be pretty decent so far. This won't take more than a few days to finish (I've got actual work commitments, so obviously this is somewhat lower priority). 

Please note there's a few minor style issues that are due to GTK issues with the conda Python environment (what I use to quickly mock up styles, even if I use C++ for real app development): it's due to `GLIBCXX_3.4.29` being missing, causing issues with `iris` and `swrast`.

Currently, the floating maximize and minimize buttons look bad, and there's a few issues with the tabs (they don't style properly, and don't show the highlight tab at all), but it's coming a long way.

![Screenshot_20210720_123103](https://user-images.githubusercontent.com/9440903/126369363-41770dcd-945c-4397-b430-a07c6f15e30a.png)
![Screenshot_20210720_123152](https://user-images.githubusercontent.com/9440903/126369367-da61de25-a90b-49bc-8081-0c34ab45f9b3.png)

**Comment by ruilvo** [comment]
Whoa! Thanks! I'll test on C++ :D

**Comment by Alexhuszagh** [comment]
Here's a few images, @ruilvo. Let me know if there are any issues, and I'll re-open it.

![Dock1](https://user-images.githubusercontent.com/9440903/126407137-6deb081c-3826-433c-9e30-b169214b3047.png)
![Dock2](https://user-images.githubusercontent.com/9440903/126407138-ef7ba2e5-3a7e-46d6-a770-8d5db5d3ccef.png)
![Dock3](https://user-images.githubusercontent.com/9440903/126407140-e4fd4207-e76f-492b-9909-a20c013d6a4d.png)
![Dock4](https://user-images.githubusercontent.com/9440903/126407141-577813e2-20ae-4a18-aefd-130761aceeaa.png)
![Dock5](https://user-images.githubusercontent.com/9440903/126407142-9d913eb8-bf55-475c-9bb2-de0e4fb2b8e5.png)

**Comment by Alexhuszagh** [comment]
Oh @ruilvo, by default, support for ADS isn't enabled. To enable it, you can pass:

```bash
python configure.py --extensions=advanced-docking-system --styles=all
```

You can then use `custom.qrc` (and rename it as you wish) to use it with the ADS support.

**Comment by ruilvo** [comment]
It seems to be working :D
Thanks!

![imagem](https://user-images.githubusercontent.com/8402646/126407503-6b16c105-ef1f-4c5d-b68c-21ff9ec9cb9b.png)

**Comment by Alexhuszagh** [comment]
Let me know if anything doesn't work as expected, I'd be happy to fix any issues.

**Comment by ruilvo** [comment]
Have you noticed that when resizing, sometimes there's a funny glitch with the svg? Notice the minimize one:
https://i.gyazo.com/6c30b0bd3a702451ce7799c6e751cda6.mp4

**Comment by Alexhuszagh** [comment]
> Have you noticed that when resizing, sometimes there's a funny glitch with the svg? Notice the minimize one:
> https://i.gyazo.com/6c30b0bd3a702451ce7799c6e751cda6.mp4

No, it doesn't replicate for me on Linux. When I get access to my Windows computer, I can try to fix it. I'm currently out-of-town, so it will be a week before I get a chance to.
