### ISSUE TITLE
Question for MIT compliance

### ISSUE THREAD

**Issue by mapron** [Alexhuszagh/BreezeStyleSheets#23]
Hi, thank you for your project, I added generated theme into my opensource (MIT) project:
https://github.com/mapron/d2modgen
I already added link in "Used thirdparty products" in readme.md. Though not sure if it's enough.
I am not adding your sources to my repo; also, I do not distribute full license with binary package (so in binary release, you can't see thirdarty license).
Is it ok for you? Fair enough?

**Comment by Alexhuszagh** [comment]
That should be sufficient: you're not including the sources, are crediting the authors of the theme, and are mentioning the license compliance information and linking to the original source. I'm not a copyright lawyer, but I see no issue with this. Thanks for checking in.
