### ISSUE TITLE
Can't find dark.qss?

### ISSUE THREAD

**Issue by antonsanchez** [Alexhuszagh/BreezeStyleSheets#66]
Hello,

When I try to build, I get the following error:

P:\BreezeStyleSheets>python configure.py --compiled-resource breeze_resources.py
Traceback (most recent call last):
  File "configure.py", line 371, in <module>
    sys.exit(main())
  File "configure.py", line 368, in main
    configure(parse_args(argv))
  File "configure.py", line 358, in configure
    subprocess.check_call(
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 359, in check_call
    retcode = call(*popenargs, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

UPDATE: I got this working by getting rid of "--compiled-resource breeze_resources.py" This worked, however the window title bar is still white. Any idea why that is?

Thanks!

**Comment by Alexhuszagh** [comment]
For the first issue, it's possible it's a bug on my end. As for the second one, Windows does not allow you to change the Window titlebar style through Qt. The only solution is to remove it entirely, and implement your own.

An example doing so can be found [here](https://github.com/Alexhuszagh/BreezeStyleSheets/blob/main/example/titlebar.py). Please note the caveats described here:

https://github.com/Alexhuszagh/BreezeStyleSheets/blob/9ade91d4da1dd0eaf885793d61f8455ca08065d3/example/titlebar.py#L98-L100

**Comment by Alexhuszagh** [comment]
FYI: if you're on Windows, then you might be able to use platform-specific APIs (the WinAPI) to change the titlebar style, but this isn't cross-platform nor available in Qt. As far as implementing your own custom titlebar, if you ever plan on having Linux users, it's a terrible idea due to design choices in Wayland (X11 works fine).

**Comment by Alexhuszagh** [comment]
Closed since this is now documented and the rest is platform limitations with how titlebars work.
