### ISSUE TITLE
[BUG] Menu items keep hovered display

### ISSUE THREAD

**Issue by felipefarinon** [Alexhuszagh/BreezeStyleSheets#73]
## Description

The menu items are keeping their "hovered" display when I go from one menu item to another, without leaving the menu area.

![GIF 12-8-2022 8-25-48 AM](https://user-images.githubusercontent.com/17036813/206458023-6875e030-d800-4c48-bab6-ebcf069eb6ea.gif)

## Prerequisites

- Qt version: 6
- Theme: Dark and Light
- OS: Windows 10

**Comment by Alexhuszagh** [comment]
Replicated locally, this affects both Qt5 and Qt6. Thanks for reporting.
