### ISSUE TITLE
[QUESTION] Flat buttons with border

### ISSUE THREAD

**Issue by felipefarinon** [Alexhuszagh/BreezeStyleSheets#74]
## Question
I've added a push button to my application, with _flat_ set to true. However, it still has borders on, contrary to the native version of the button.

Is this the expected behavior?

Dark Theme (On Light Theme it also has borders):
![image](https://user-images.githubusercontent.com/17036813/206459969-af20df1e-f893-4644-bd8b-3e20a10fc50a.png)

Windows 10 Native:
![image](https://user-images.githubusercontent.com/17036813/206460462-e1f7623d-19ac-4992-9ab2-25c40861cefb.png)

**Comment by felipefarinon** [comment]
I believe they could be visually similar to the QToolButtons.

**Comment by Alexhuszagh** [comment]
This is a bug, since well, it's supposed to be flat. It also contrasts with KDE's Breeze themes themselves, which is a stylistic inspiration for these stylesheets.
