### ISSUE TITLE
[QUESTION] Mismatching visual styles in the Gallery gif

### ISSUE THREAD

**Issue by felipefarinon** [Alexhuszagh/BreezeStyleSheets#76]
## Question
I've two differences in my application to the visual styles that appear in the gallery gif [1].

1. The TreeWidget background in the gallery is white in the Light theme. But in my application it shows as grey.
2. Several widgets in the Gallery show borders. But in my application, they don't have them.

Gallery:
![image](https://user-images.githubusercontent.com/17036813/206463239-7e90bfad-fbb1-4215-89d2-dcbc1e33ed98.png)

Application:
![image](https://user-images.githubusercontent.com/17036813/206463531-6948cb12-4c3a-486f-a24c-c7dc94ccc806.png)

[1] https://github.com/Alexhuszagh/BreezeStyleSheets/blob/main/assets/Breeze.gif

**Comment by Alexhuszagh** [comment]
I'm assuming all the environment information provided is the same as before?

> Qt version: 6
> Theme: Dark and Light
> OS: Windows 10

**Comment by felipefarinon** [comment]
Exactly. That's my environment.

**Comment by Alexhuszagh** [comment]
Can you provide more specific details? I've confirmed that this still works on my end with [widgets.py](/example/widgets.py).

The command I'm running from the repository root is:

```bash
python example/widgets.py --stylesheet dark --set-app-palette --pyqt6
```

![2022-12-08 16_22_14-Sample BreezeStyleSheets application](https://user-images.githubusercontent.com/9440903/206579750-01530064-5ce7-493e-a63f-f0971a7b5790.png)
![2022-12-08 16_22_49-Sample BreezeStyleSheets application](https://user-images.githubusercontent.com/9440903/206579845-0273d5f4-cc48-418b-af6d-de3060dcc562.png)

The view is under `Tab 2` on the right-hand tab widget. The widget itself here is a standard `QTreeWidget`, and I'm running both Qt5 and Qt6 under Windows 10. Likewise, the unittests are passing on my end:

```bash
py -3.9 test/ui.py --widget tree --stylesheet light
py -3.9 test/ui.py --widget editable_tree --stylesheet light
```

![2022-12-08 16_26_30-Unittest for tree](https://user-images.githubusercontent.com/9440903/206580387-db8556af-6b13-4c25-b534-776a53bcbc4c.png)
![2022-12-08 16_27_23-Unittest for editable_tree](https://user-images.githubusercontent.com/9440903/206580493-92439ab0-f41e-4d90-a21b-b82739f958d8.png)

I probably need a unittest for `QTreeWidgetItem` widgets with icons.

**Comment by felipefarinon** [comment]
The behavior of your tests are the same I get with my application.

But the gif in the Gallery of the repo (https://github.com/Alexhuszagh/BreezeStyleSheets/blob/main/assets/Breeze.gif), has a white background for QTreeWidget instead of grey. So I was wondering which is the correct color.

![Capture](https://user-images.githubusercontent.com/17036813/206581802-c5e5253c-1a16-4d56-b268-72638d47bb71.PNG)

**Comment by Alexhuszagh** [comment]
Ah thank you, the image reflects a prior version and has since been updated. I'll add updated images to the gallery.
