### ISSUE TITLE
[QUESTION] Possibility to use a non-project-root directory?

### ISSUE THREAD

**Issue by BruebachL** [Alexhuszagh/BreezeStyleSheets#81]
## Question
Hi. First of, thanks for your work on this, it looks fantastic!
I'm trying to include this stylesheet in a PyQt5 project (I can't seem to get it to compile for Qt5 but it looks like Qt6 works just as well.)
My actual issue is the following. I've moved this repository to <project_root>/ui/BreezeStylesheets/ and then ran 
python configure.py --compiled-resource breeze_resources.py

I include it with
import ui.BreezeStyleSheets.breeze_resources

and it seems to apply, at the very least. However, qt.svg spits out a whole list of file errors on launch, which makes me think icons are not being loaded.
qt.svg: Cannot open file '/<project_root>/dark:minimize.svg', because: No such file or directory [sic, this is cut off]

Which folders and files from this repository does the compiled stylesheet depend on (i.e. what do I need to copy and paste) and is there a way to adjust configure.py to use a different non-project-root path (i.e. a subdirectory of the project root)?

**Comment by Alexhuszagh** [comment]
So [breeze_resources.py](https://github.com/Alexhuszagh/BreezeStyleSheets/blob/main/breeze_resources.py) has everything in a single blob, and the structure looks somewhat like this. It shouldn't spit out any errors, since every image is bundled in that single blob (partially why I use such small, stripped SVG files).

```python
from PyQt5 import QtCore

qt_resource_data = b"\
\x00\x00\x01\x1a\
\x3c\
...
"

qt_version = [int(v) for v in QtCore.qVersion().split('.')]
if qt_version < [5, 8, 0]:
    rcc_version = 1
    qt_resource_struct = qt_resource_struct_v1
else:
    rcc_version = 2
    qt_resource_struct = qt_resource_struct_v2

def qInitResources():
    QtCore.qRegisterResourceData(rcc_version, qt_resource_struct, qt_resource_name, qt_resource_data)

def qCleanupResources():
    QtCore.qUnregisterResourceData(rcc_version, qt_resource_struct, qt_resource_name, qt_resource_data)

qInitResources()
```

So as long as you're compiling to build that resources.py, it should be able to be run from any root. How are you setting the stylesheet and creating the project directory? A simple example I created was:

```
/path/to/dir/
  script.py
  nonroot/
    __init__.py
    src/
      __init__.py
      breeze_resources.py
```

The contents of `breeze_resources.py` is the same as before, and the contents of `script.py` are:

```python
import sys
from PyQt5 import QtCore, QtGui, QtWidgets

from nonroot.src import breeze_resources


def read_stylesheet(path):
    file = QtCore.QFile(path)
    file.open(QtCore.QFile.ReadOnly | QtCore.QFile.Text)
    stream = QtCore.QTextStream(file)
    return stream.readAll()


def main():
    'Application entry point'

    app = QtWidgets.QApplication(sys.argv)
    window = QtWidgets.QMainWindow()
    app.setStyleSheet(read_stylesheet(':/dark/stylesheet.qss'))
    window.resize(1068, 824)

    central = QtWidgets.QWidget(window)
    layout = QtWidgets.QHBoxLayout(central)
    window.setCentralWidget(central)

    tree = QtWidgets.QTreeWidget(central)
    tree.setHeaderLabel('Tree 1')
    item1 = QtWidgets.QTreeWidgetItem(tree, ['Row 1'])
    item2 = QtWidgets.QTreeWidgetItem(tree, ['Row 2'])
    item3 = QtWidgets.QTreeWidgetItem(item2, ['Row 2.1'])
    item3.setFlags(item3.flags() | QtCore.Qt.ItemIsUserCheckable)
    item3.setCheckState(0, QtCore.Qt.Unchecked)
    item4 = QtWidgets.QTreeWidgetItem(item2, ['Row 2.2'])
    item5 = QtWidgets.QTreeWidgetItem(item4, ['Row 2.2.1'])
    item6 = QtWidgets.QTreeWidgetItem(item5, ['Row 2.2.1.1'])
    item7 = QtWidgets.QTreeWidgetItem(item5, ['Row 2.2.1.2'])
    item7.setFlags(item7.flags() | QtCore.Qt.ItemIsUserCheckable)
    item7.setCheckState(0, QtCore.Qt.Checked)
    item8 = QtWidgets.QTreeWidgetItem(item2, ['Row 2.3'])
    item8.setFlags(item8.flags() | QtCore.Qt.ItemIsUserTristate)
    item8.setCheckState(0, QtCore.Qt.PartiallyChecked)
    item9 = QtWidgets.QTreeWidgetItem(tree, ['Row 3'])
    item10 = QtWidgets.QTreeWidgetItem(item9, ['Row 3.1'])
    item11 = QtWidgets.QTreeWidgetItem(tree, ['Row 4'])
    layout.addWidget(tree)

    window.show()
    return app.exec_()


if __name__ == '__main__':
    sys.exit(main())
```

Which imports it from a submodule, and then reads the stylesheet, and creates a sample widget. Can you provide a working example by any chance?

**Comment by BruebachL** [comment]
Thank you for the prompt reply. The issue was not enough familiarity (or faith) in QT's resource system. I used your example but what I did was, I set an absolute path rather than the relative ':/dark/stylesheet.qss'. I was not aware that QT was that good about locating resources.

Thank you once again for the help and your work on this :)

**Comment by Alexhuszagh** [comment]
Glad to see everything works for Qt5. Since PyQt6 uses a different resource system, if there's any issues with a Qt6 ecosystem, feel free to submit another issue or open a discussion.
