### ISSUE TITLE
[BUG] Tab header disaligned and with double stroke

### ISSUE THREAD

**Issue by felipefarinon** [Alexhuszagh/BreezeStyleSheets#82]
## Description

The image below shows two issues. In red, the tab header is not aligned with the border of the tab widget. In blue, I believe that there shouldn't be a grey stroke below the "Tab 1" and that "Tab 2" shouldn't have a double stroke (making it look like a thicker border).

![image](https://user-images.githubusercontent.com/17036813/211206465-d7debe8d-081d-4ec9-bfee-faeee791eed5.png)

## Prerequisites

- Qt version: 6
- Theme: Dark, Light
- OS: Windows 10

**Comment by Alexhuszagh** [comment]
The misalignment is confirmed in [widgets.py](https://github.com/Alexhuszagh/BreezeStyleSheets/blob/8f88ce4f714bdeefe139dcdf2c86f71f955836a0/example/widgets.py), however, the double border is intentional to make the difference between the active and inactive tab more obvious.

**Comment by Alexhuszagh** [comment]
This still affects it at 2x scale so it's clearly not an artifact (which should be fixed even if it was).

![2024-09-05 19_40_12-Sample BreezeStyleSheets application](https://github.com/user-attachments/assets/7f6ee835-bdb2-49e4-97c5-420214940cf9)

**Comment by Alexhuszagh** [comment]
These are the new images of how the tabs looks.

![2024-09-05 20_06_20-Unittest for tabwidget_bottom](https://github.com/user-attachments/assets/d8c00043-7ae6-49de-a37f-642e6b84784b)
![2024-09-05 20_05_30-Unittest for tabwidget_right](https://github.com/user-attachments/assets/489a3b7f-3e91-4701-bf8f-4f580701b571)
![2024-09-05 20_05_44-@_JungKi_ - Discord](https://github.com/user-attachments/assets/5013276f-b050-4a56-8745-cea1b85d781f)
![2024-09-05 20_06_02-Unittest for tabwidget_top](https://github.com/user-attachments/assets/f6ba35de-200b-4c93-83d1-94e8412955b9)

**Comment by felipefarinon** [comment]
Great, thanks!

**Comment by Alexhuszagh** [comment]
Thanks for your patience by the way on this.
