### ISSUE TITLE
[BUG] Moving a tab left makes its text disappear

### ISSUE THREAD

**Issue by felipefarinon** [Alexhuszagh/BreezeStyleSheets#83]
## Description

Whenever I move a tab (TabWidget with movable=true) left, the text disappears while I'm dragging it. But when I move it right, the text is kept.

![GIF 1-8-2023 11-02-35 AM](https://user-images.githubusercontent.com/17036813/211206778-8bc6521d-e543-4ba2-acdb-cf812a9bd1f7.gif)

## Prerequisites

- Qt version: 6
- Theme: Dark, Light
- OS: Windows 10

**Comment by Alexhuszagh** [comment]
I can't replicate this with PySide2, PySide6, PyQt5, or PyQt6 as of the latest versions. You can test this with our moveable tab test case by running:

```bash
python test/ui.py --qt-framework "${engine}" --stylesheet dark --widget movable_tabwidget
```

Which produces this output.
![BreezeStyleSheets Issue 83](https://github.com/user-attachments/assets/b5661ec4-8104-4259-bd2c-071608197b4c)

I'll be happy to reopen this if it's still an issue, but please try the latest versions first.
