### ISSUE TITLE
How to use stylesheet with ADS focushighlighting?

### ISSUE THREAD

**Issue by Olo420** [Alexhuszagh/BreezeStyleSheets#85]
How to use and customize stylesheet for Advanced Docking System if DockerManager configuration flag for  Focushighlighting is set true? Thanks your for your answear.

**Comment by Alexhuszagh** [comment]
I'll see if I can find a minimum, working example of it working in PySide6 and then slowly add in styles to see what might be conflicting.

**Comment by Alexhuszagh** [comment]
I should have a solution with this and can implement it in directly. I've also added in some tests to ensure this works well.

**Comment by Alexhuszagh** [comment]
These are the previews after the changes,

![2024-09-06 00_25_33-python](https://github.com/user-attachments/assets/ea093ee8-325d-47cf-8a3a-65a5c27b2bf7)
![2024-09-06 00_25_04-python](https://github.com/user-attachments/assets/4ade739d-8b9a-43d4-ac96-8c91a96facb1)
